name: Deploy Tiddlywiki To Github Pages

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    permissions:
      contents: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v2-beta
        with:
          node-version: '18'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            ~/.pnpm-store
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install -g pnpm && pnpm install

      - name: Build Library and static website
        run: pnpm run publish

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: ./dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_PERSONAL_ACCESS_TOKEN }}
          NETLIFY_DEPLOY_TO_PROD: true
          NETLIFY_SITE_ID: 1e7ee811-e6ff-43de-9bb3-3fa107d4fa23
          build_directory: ./dist
          NETLIFY_DEPLOY_MESSAGE: "Deployed from GitHub action"
          install_command: "echo Skipping installing the dependencies"
          build_command: "echo Skipping building the web files"
